### ISSUE TITLE
What  can you do with the brewery dump files?

### ISSUE THREAD

**Issue by timtijmen2** [Patbox/brewery#19]
I thought you might be able to make your own beverages with them, but if thats true i cant figure out how to get them to work.
Can you explain what they are and how they work?
Thanks in advance

**Comment by Patbox** [comment]
These files can be used as template/base to create your own brews. To add new ones you need to create datapack. You can check more about that here! 

https://github.com/Patbox/brewery/blob/1.20.2/DATAPACK.md
And here about general info about datapacks: https://minecraft.wiki/w/Tutorials/Creating_a_data_pack
through you don't need anything after `Functions` sections

**Comment by timtijmen2** [comment]
Ah thank you, that helped a lot but i cant figure out how to change the amount of time it takes to cook.
Can you help me with that?

` "cooking_quality_multiplier": "cos(clamp((age / 60 - 5.0) * 0.5, -2, 2))",`
