### ISSUE TITLE
Wine and Glow Wine share the same recipe.

### ISSUE THREAD

**Issue by enjarai** [Patbox/brewery#2]
In the default recipe set, Wine and Glow Wine both require 5 Sweet Berries. This is probably the reason why trying to brew wine fails instantly every time. I assume glow wine is supposed to use Glow Berries?

**Comment by Patbox** [comment]
Oh yep, missed that somehow. Through it shouldn't fail brewing, just end up with first one

**Comment by enjarai** [comment]
Yea I just tried fixing the Glow Wine with a datapack, which worked, but the normal wine still cant be brewed. It fails instantly when placed into the barrel. All other brews we've tried so far seem to work.
