### ISSUE TITLE
Hmmm, just cauldron drinks don't work.

### ISSUE THREAD

**Issue by MrPlayerYork** [Patbox/brewery#3]
I tried to make tea and i get a mixture instead of a drink.

**Comment by Patbox** [comment]
Tried locally and I can't confirm. Are you sure you got right amount of ingredients/time?

**Comment by MrPlayerYork** [comment]
1 oak sappling for 5 minutes, in a cauldron, collected by glass bottle. Am I correct in the way to make it?

**Comment by Patbox** [comment]
Nope, it uses oak leavas. You should check book of brewery for extra recipes

**Comment by MrPlayerYork** [comment]
i'm sorry, guess i'm dumb and can't read just dumb :P sorry, i thought it was sapplings.

**Comment by MrPlayerYork** [comment]
i'm sorry, guess i'm dumb and can't read just dumb :P sorry, i thought it was sapplings.
