### ISSUE TITLE
for some reason not working as servert siide

### ISSUE THREAD

**Issue by user99000** [Patbox/brewery#35]
![image](https://github.com/user-attachments/assets/dcd6f514-d0ee-4749-bdd6-921eceeb9505)

**Comment by user99000** [comment]
even if i add it to user side, still not wroking

**Comment by user99000** [comment]
[latest.log](https://github.com/user-attachments/files/16970099/latest.log)
latest log from client (server didn't show anything in console)

**Comment by Patbox** [comment]
Thats weird, can you send list of mods and `/polymer registry-export` from server

**Comment by Patbox** [comment]
Ok after checking, server has some different brewery mod, not mine.
