### ISSUE TITLE
[Datapack Help] How can I change the cooking and/or aging time?

### ISSUE THREAD

**Issue by rfnkrbhhj** [Patbox/brewery#39]
I don't know where to ask this, but I can't seem to find a way to change the aging and cooking time of a custom drink using datapacks? I tried reading the datapack page but couldn't figure it out, is there an exmplanation?

**Comment by parkouristik93** [comment]
We have 2 parameters in the recipe: 
"cooking_time_multiplier" (Formula for getting value in range of 0-1)
"base_quality_value" (10 if you don't use "barrel_definitions", formula for getting value in range of 0-10)
You basically just change some values in quotes after them and here ya go.

If you need any further help, use Patbox's discord, I'm more active there :p

**Comment by parkouristik93** [comment]
# Vanilla Brewery uses 2 formulas. Let's look inside beer's recipe in graphs:
**Cooking time multiplier**
https://www.desmos.com/calculator/tfm6boqcqd
`cos(clamp((age / 60 - <Amount of minutes>) * 0.33, -2, 2))` (beer uses 8)
**Base quality_value**
https://www.desmos.com/calculator/cdlg9ecviv?
`smooth_value_days(<MINIMUM_TIME_FOR_BEST>, <TIME_WITHOUT_CHANGING>, <FALLOUT_TIME>, age)*10` (3.5/2.0/5.0 respectively)
`smooth_value_minutes(<MINIMUM_TIME_FOR_BEST>, <TIME_WITHOUT_CHANGING>, <FALLOUT_TIME>, age)*10`
`smooth_value_seconds(<MINIMUM_TIME_FOR_BEST>, <TIME_WITHOUT_CHANGING>, <FALLOUT_TIME>, age)*10`
DON'T FORGET ABOUT __*10 __ WHEN USING THE FORMULA FOR AGING.

Issue closed.
