### ISSUE TITLE
Connectivity breaks polymer (issue on their side)

### ISSUE THREAD

**Issue by netcore10** [Patbox/brewery#4]
https://paste.atlauncher.com/view/4d5acf84-2794-4c1f-8587-8e1b385e19b9

The barrels also turned invisible and caused a crash when i right clicked the spigot.

**Comment by Patbox** [comment]
Does this happen on singleplayer?

**Comment by Patbox** [comment]
Ok, can't replicate it with just sodium (and few other mods). Can you replicate it with some consistent setup? If so, please try removing mods (on copy/creative save) until it stops crashing

**Comment by netcore10** [comment]
I'll give it a shot and get back to you if i find it. (Though it might take quite some time)

**Comment by Patbox** [comment]
Ideally you should try by removing half of mods (and switching them if it works). Ofc while keeping required libraries

**Comment by netcore10** [comment]
Okay, so i loaded up the world and the barrel works. Until spigot is broken and placed again, it turns invisable. Still removing mods, but i dunno if that info helps.

**Comment by netcore10** [comment]
Also tapping f3 and T fixes it until one get's placed again. So that helps me get closer.

**Comment by netcore10** [comment]
Sadly not, i had to go for dinner so i'm still chugging away. Want me to close this issue for now and get back to you if i find the issue?

**Comment by netcore10** [comment]
Could it also be the quilt loader? (It uses fabric api but that might be a problem too)

**Comment by Patbox** [comment]
It shouldn't be related and I prefer issue open

**Comment by netcore10** [comment]
Gotcha, I'll let you know if i find it.

**Comment by Patbox** [comment]
Try removing connectivity mod

**Comment by netcore10** [comment]
Yeah that did it! It's connectivity! I also have another compatability problem, should i post another issue?
