### ISSUE TITLE
Crashes If Opening barrel By clicking on spigot, Barrel also Doesn't render right 

### ISSUE THREAD

**Issue by RosenheimL** [Patbox/brewery#40]
Simple Crash Report -
https://mclo.gs/9Xf4AZW

Also Providing a Picture of the rendering issue, with and without shaders enabled, Including the behavior of the barrel existing after being opened
![2024-12-21_08 23 48](https://github.com/user-attachments/assets/3cafb456-29c9-4323-9cf1-d523bf74d257)
![2024-12-21_08 24 07](https://github.com/user-attachments/assets/df1e81d2-9f42-4652-a88a-66584edbd2cb)
![2024-12-21_08 24 17](https://github.com/user-attachments/assets/e320d7a7-b711-4a32-a2b8-b3baa67d44c8)

**Comment by Patbox** [comment]
Try installing latest polymer version
